www/src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AuthorRepository::class)
 */
class Author
{


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;
    /**
     * @ORM\Column(type="integer")
     */
    private $count_books;


    public function __toString()
    {
        return $this->name;
    }
    /**
     * @return mixed
     */
    public function getCountBooks()
    {
        return $this->count_books;
    }

    /**
     * @param mixed $count_books
     */
    public function setCountBooks($count_books): void
    {
        $this->count_books = $count_books;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

www/src/Form/AuthorType.php
<?php

namespace App\Form;

use App\Entity\Author;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AuthorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Author::class,
        ]);
    }
}

www/src/Controller/AuthorController.php
<?php

namespace App\Controller;

use App\Entity\Author;
use App\Form\AuthorType;
use App\Repository\AuthorRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/author")
 */
class AuthorController extends AbstractController
{
    /**
     * @Route("/", name="app_author_index", methods={"GET"})
     */
    public function index(AuthorRepository $authorRepository): Response
    {
        return $this->render('author/index.html.twig', [
            'authors' => $authorRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_author_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AuthorRepository $authorRepository): Response
    {
        $author = new Author();
        $form = $this->createForm(AuthorType::class, $author);
        $form->handleRequest($request);
        $author->setCountBooks(0);

        if ($form->isSubmitted() && $form->isValid()) {
            $author->setCountBooks(0);

            $authorRepository->add($author);
            return $this->redirectToRoute('app_author_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('author/new.html.twig', [
            'author' => $author,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_author_show", methods={"GET"})
     */
    public function show(Author $author): Response
    {
        return $this->render('author/show.html.twig', [
            'author' => $author,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_author_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Author $author, AuthorRepository $authorRepository): Response
    {
        $form = $this->createForm(AuthorType::class, $author);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $authorRepository->add($author);
            return $this->redirectToRoute('app_author_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('author/edit.html.twig', [
            'author' => $author,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_author_delete", methods={"POST"})
     */
    public function delete(Request $request, Author $author, AuthorRepository $authorRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$author->getId(), $request->request->get('_token'))) {
            $authorRepository->remove($author);
        }

        return $this->redirectToRoute('app_author_index', [], Response::HTTP_SEE_OTHER);
    }
}

www/templates/author/_delete_form.html.twig
<form method="post" action="{{ path('app_author_delete', {'id': author.id}) }}" onsubmit="return confirm('Вы действительно хотите удалить данные автора?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ author.id) }}">
    <button class="btn">Удалить</button>
</form>

www/templates/author/_form.html.twig
{{ form_start(form) }}
<div class="form-group">
    <div class="form-group">
        {{ form_row(form.name, {'label' : 'ФИО','attr': {'class': 'form-control'}}) }}
    </div>
    <button class="btn {{ button_color|default('btn-outline-primary') }}  mt-3">{{ button_label|default('Сохранить') }}</button>
</div>
{{ form_end(form) }}

www/templates/author/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Редактировать запись{% endblock %}

{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Редактирование данных автора</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_author_index') }}">
                    Показать список авторов
                </a>
            </div>
            <div class="card-body">
                {% include 'author/_form.html.twig' with {'button_label': 'Обновить', 'button_color': 'btn-outline-success'}  %}
            </div>
        </div>
    </div>
{% endblock %}

www/templates/author/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Список авторов{% endblock %}

{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Список авторов</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-primary" href="{{ path('app_author_new') }}">
                    Добавить данные автора
                </a>
                <a class="btn btn-outline-primary" href="{{ path('app_book_index') }}">
                    Перейти в список книг
                </a>
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <tr>
                        <th>Id</th>
                        <th>ФИО</th>
                        <th>Кол-во книг</th>
                        <th width="240px">Действия</th>
                    </tr>
                    {% for author in authors %}
                        <tr>
                            <td>{{ author.id }}</td>
                            <td>{{ author.name }}</td>
                            <td>{{ author.countBooks }}</td>

                            <td>
                                <form method="post" action="{{ path('app_author_delete', {'id': author.id}) }}" onsubmit="return confirm('Вы действительно хотите удалить запись?');">
                                    <a
                                            class="btn btn-outline-info"
                                            href="{{ path('app_author_show', {'id': author.id}) }}">
                                        Подробнее
                                    </a>
                                    <a
                                            class="btn btn-outline-success"
                                            href="{{ path('app_author_edit', {'id': author.id}) }}">
                                        Редактирование
                                    </a>

                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ author.id) }}">
                                    <button class="btn btn-outline-danger">Удалить</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

{% endblock %}

www/templates/author/new.html.twig
{% extends 'base.html.twig' %}
 
{% block title %}Новый автор{% endblock %}
 
{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Добавить автора</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_author_index') }}">
                    Показать список авторов
                </a>
            </div>
            <div class="card-body">
                {{ include('author/_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

www/templates/author/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Автор{% endblock %}

{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Данные автора</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_author_index') }}">
                    Показать список авторов
                </a>
            </div>
            <div class="card-body">
                <b class="text-muted">ФИО:</b>
                <p>{{ author.name }}</p>
                <b class="text-muted">Кол-во книг:</b>
                <p>{{ author.getCountBooks() }}</p>
            </div>
        </div>
    </div>
{% endblock %}