www/src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="blob")
     */
    private $image;

    /**
     * @ORM\Column(type="integer")
     */
    private $year_public;


    /**
     * @ORM\ManyToMany(targetEntity="Author")
     * @ORM\JoinTable(name="author_books",
     *     joinColumns={@ORM\JoinColumn (name="book_id", referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn (name="author_id", referencedColumnName="id")} )
     */
    protected \Doctrine\Common\Collections\Collection $authorBooks;


    /**
     * @return mixed
     */
    public function getAuthorBooks()
    {
        return $this->authorBooks;
    }

    public function getAuthorsList(){
        $str = '';

        foreach ($this->authorBooks as $authorBook){
            $str .= $authorBook->getName() . ';';
        }

        return $str;
    }
    /**
     * @param $authorBooks
     */
    public function setAuthorBooks($authorBooks): void
    {
        $this->authorBooks = $authorBooks;
    }
    public function addBook(Book $book): self
    {
        if (!$this->authorBooks->contains($book)) {
            $this->authorBooks->add($book) ;
        }
        $this->authorBooks[] = $book;
        return $this;
    }
    public function removeBook(Book $book): self
    {
        $this->authorBooks->removeElement($book);
        return $this;
    }


//    public function getAuthors(): Collection
//    {
//        return $this->authors;
//    }
//
//    public function addAuthor(Author $author): self
//    {
//        if (!$this->authors->contains($author)) {
//            $this->authors->add($author) ;
//        }
//        return $this;
//    }
//    public function removeAuthor(Author $author): self
//    {
//        $this->authors->removeElement($author);
//        return $this;
//    }
//    /**
//     * @param ArrayCollection $authors
//     */
//    public function setAuthors(ArrayCollection $authors): void
//    {
//        $this->authors = $authors;
//    }
//
//    public function __construct()
//    {
//        $this->authors = new ArrayCollection();
//    }
//
//    /**
//     * @return Collection|Author[]
//     */
//

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        $imageBase64 = '';
        if (null === $this->image) {
            return null;
        }
            $data = stream_get_contents($this->image);
            fclose($this->image);
        return base64_encode($data);

    }

    public function setImage($image): self
    {
        $this->image = $image;


        return $this;
    }

    public function getYearPublic(): ?int
    {
        return $this->year_public;
    }

    public function setYearPublic(int $year_public): self
    {
        $this->year_public = $year_public;

        return $this;
    }

}

www/src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use Doctrine\DBAL\Types\BlobType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('image', FileType::class,[
                'mapped' => false,
                'attr' => [
                    'accept' => "image/*"
                ],
            ])
            ->add('year_public')
            ->add('authorBooks')
        ;
        //FileType::class
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

www/src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Author;
use App\Entity\Book;
use App\Form\BookType;
use App\Repository\AuthorRepository;
use App\Repository\BookRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Query;
use Doctrine\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/book")
 */
class BookController extends AbstractController
{

    /**
     * @Route("/", name="app_book_index", methods={"GET"})
     */
    public function index(BookRepository $bookRepository): Response
    {
//        $link = mysqli_connect(getenv('DB_HOST'), getenv('DB_USER'), getenv('DB_PASSWORD'));
//
//        if(!mysqli_select_db($link,'test')){
//            mysqli_query($link,'CREATE DATABASE test');
//            mysqli_select_db($link,'test');
//            mysqli_query($link,'CREATE TABLE author (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, count_books INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
//            mysqli_query($link,'CREATE TABLE book (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, description VARCHAR(255) NOT NULL, image LONGBLOB NOT NULL, year_public INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
//            mysqli_query($link,'INSERT INTO author(name,count_books) VALUES (\'Иванов Иван Петрович\', 0)');
//            mysqli_query($link,'INSERT INTO author(name,count_books) VALUES (\'Иванов Ивана Петровна\', 0)');
//            mysqli_query($link,'INSERT INTO author(name,count_books) VALUES (\'Иванович Иван Петровичввв\', 0)');
//            mysqli_query($link,'INSERT INTO book(name,description,image,year_public) VALUES (\'Золушка\',\'Из мультфильма\',\'\', 1996)');
//            mysqli_query($link,'INSERT INTO book(name,description,image,year_public) VALUES (\'Трое из Лас-Вегаса\',\'Из мультфильма\',\'\', 1997)');
//            mysqli_query($link,'INSERT INTO book(name,description,image,year_public) VALUES (\'Побез из замка\',\'Из мультфильма\',\'\', 2022)');
//            mysqli_query($link,'CREATE TABLE author_books (book_id INT NOT NULL, author_id INT NOT NULL, INDEX IDX_5C930A5F16A2B381 (book_id), INDEX IDX_5C930A5FF675F31B (author_id), PRIMARY KEY(book_id, author_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
//            mysqli_query($link,'ALTER TABLE author_books ADD CONSTRAINT FK_5C930A5F16A2B381 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE ON UPDATE CASCADE ');
//            mysqli_query($link,'ALTER TABLE author_books ADD CONSTRAINT FK_5C930A5FF675F31B FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE ON UPDATE CASCADE ');
//        }
        return $this->render('book/index.html.twig', [
            'books' => $bookRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_book_new", methods={"GET", "POST"})
     */
    public function new(Request $request, BookRepository $bookRepository): Response
    {
        $book = new Book();
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form['image']->getData();
            $book->setImage(file_get_contents($file));
            $bookRepository->add($book);
            foreach ($book->getAuthorBooks() as $authorBook){
                $bookRepository->setCountBooksOfAuthor($authorBook);
            }
            return $this->redirectToRoute('app_book_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('book/new.html.twig', [
            'book' => $book,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_book_show", methods={"GET"})
     */
    public function show(Book $book): Response
    {
        return $this->render('book/show.html.twig', [
            'book' => $book,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_book_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Book $book, BookRepository $bookRepository): Response
    {
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form['image']->getData();
            $book->setImage(file_get_contents($file));
            $bookRepository->add($book);
            foreach ($book->getAuthorBooks() as $authorBook){
                $bookRepository->setCountBooksOfAuthor($authorBook);
            }
            return $this->redirectToRoute('app_book_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('book/edit.html.twig', [
            'book' => $book,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_book_delete", methods={"POST"})
     */
    public function delete(Request $request, Book $book, BookRepository $bookRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$book->getId(), $request->request->get('_token'))) {
            $bookRepository->remove($book);
        }

        return $this->redirectToRoute('app_book_index', [], Response::HTTP_SEE_OTHER);
    }
}

www/templates/book/_delete_form.html.twig
<form method="post" action="{{ path('app_book_delete', {'id': book.id}) }}" onsubmit="return confirm('Вы действительно хотите удалить данные книги?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ book.id) }}">
    <button class="btn">Удалить</button>
</form>

www/templates/book/_form.html.twig
{{ form_start(form) }}
<div class="form-group">
    <div class="form-group">
        {{ form_row(form.name, {'label' : 'Название','attr': {'class': 'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.description, {'label' : 'Описание','attr': {'class': 'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.image, {'label' : 'Обложка','attr': {'class': 'form-control' }}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.year_public, {'label' : 'Год публикации','attr': {'class': 'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.authorBooks, {'label' : 'Список авторов','attr': {'class': 'form-control'}}) }}
    </div>
    <button class="btn {{ button_color|default('btn-outline-primary') }}  mt-3">{{ button_label|default('Сохранить') }}</button>
</div>
{{ form_end(form) }}

www/templates/book/edit.html.twig
{#<!DOCTYPE html>#}

{#<title>Редактировать</title>#}

{#{% block body %}#}
{#    <h1>Обновление</h1>#}

{#    {{ include('book/_form.html.twig', {'button_label': ',Обновить'}) }}#}

{#    <a href="{{ path('app_book_index') }}">Назад</a>#}

{#    {{ include('book/_delete_form.html.twig') }}#}
{#{% endblock %}#}
{% extends 'base.html.twig' %}

{% block title %}Редактировать запись{% endblock %}

{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Редактирование данных книги</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_book_index') }}">
                    Показать список книг
                </a>
            </div>
            <div class="card-body">
                {% include 'book/_form.html.twig' with {'button_label': 'Обновить', 'button_color': 'btn-outline-success'}  %}
            </div>
        </div>
    </div>
{% endblock %}

www/templates/book/index.html.twig
{#<!DOCTYPE html>#}

{#<title>Список книг</title>#}
{#<style>#}
{#    .styled-table {#}
{#        border-collapse: collapse;#}
{#        margin: 25px 0;#}
{#        font-size: 0.9em;#}
{#        font-family: sans-serif;#}
{#        min-width: 400px;#}
{#        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);#}
{#    }#}
{#    .styled-table thead tr {#}
{#        background-color: #009879;#}
{#        color: #ffffff;#}
{#        text-align: left;#}
{#    }#}

{#    .styled-table th,#}
{#    .styled-table td {#}
{#        padding: 12px 15px;#}
{#    }#}

{#    .styled-table tbody tr {#}
{#        border-bottom: 1px solid #dddddd;#}
{#    }#}

{#    .styled-table tbody tr:nth-of-type(even) {#}
{#        background-color: #f3f3f3;#}
{#    }#}

{#    .styled-table tbody tr:last-of-type {#}
{#        border-bottom: 2px solid #009879;#}
{#    }#}

{#    .styled-table tbody tr.active-row {#}
{#        font-weight: bold;#}
{#        color: #009879;#}
{#    }#}
{#</style>#}
{#{% block body %}#}
{#    <h1>Список книг</h1>#}
{#    <a href="{{ path('app_author_index') }}">Перейти к списку авторов</a>#}
{#    <table class="styled-table">#}
{#        <thead>#}
{#            <tr>#}
{#                <th>Id</th>#}
{#                <th>Название</th>#}
{#                <th>Описание</th>#}
{#                <th>Обложка</th>#}
{#                <th>Год выпуска</th>#}
{#                <th>Действия</th>#}
{#            </tr>#}
{#        </thead>#}
{#        <tbody>#}
{#        {% for book in books %}#}
{#            <tr>#}
{#                <td>{{ book.id }}</td>#}
{#                <td>{{ book.name }}</td>#}
{#                <td>{{ book.description }}</td>#}
{#                <td><img alt="" src="{{ book.image}}" /></td>#}
{#                <td>{{ book.yearPublic }}</td>#}
{#                <td>#}
{#                    <a href="{{ path('app_book_show', {'id': book.id}) }}">Показать</a>#}
{#                    <a href="{{ path('app_book_edit', {'id': book.id}) }}">Обновить</a>#}
{#                </td>#}
{#            </tr>#}
{#        {% else %}#}
{#            <tr>#}
{#                <td colspan="6">Отсувствуют данные</td>#}
{#            </tr>#}
{#        {% endfor %}#}
{#        </tbody>#}
{#    </table>#}

{#    <a href="{{ path('app_book_new') }}">Добавить</a>#}
{#{% endblock %}#}

{% extends 'base.html.twig' %}

{% block title %}Список книг{% endblock %}

{% block body %}
    <style>
        #filterInput {
            background-position: 10px 10px;
            background-repeat: no-repeat;
            width: 100%;
            font-size: 16px;
            padding: 12px 20px 12px 40px;
            border: 1px solid #ddd;
            margin-bottom: 12px;
        }
    </style>
    <script>
        function filterFunction() {
            var input, filter, table, tr,tds, td, i,j, txtValue;
            input = document.getElementById("filterInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("booksTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                tds = tr[i].getElementsByTagName("td");
                for(j = 0; j < tds.length; j++)
                {
                    if(j !== 4 || j !== 6){
                        td = tds[j];
                        if (td) {
                            txtValue = td.textContent || td.innerText;
                            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                                tr[i].style.display = "";
                                break;
                            } else {
                                tr[i].style.display = "none";
                            }
                        }
                    }
                }

            }
        }
    </script>
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Список книг</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-primary" href="{{ path('app_book_new') }}">
                    Добавить данные книги
                </a>
                <a class="btn btn-outline-primary" href="{{ path('app_author_index') }}">
                    Перейти в список авторов
                </a>
            </div>
            <div class="card-body">
                <input type="text" id="filterInput" onkeyup="filterFunction()" placeholder="Введите текст" title="Type in a name">
                <table id="booksTable" class="table table-bordered">
                    <tr>
                        <th>Id</th>
                        <th>Название</th>
                        <th>Авторы</th>
                        <th>Описание</th>
                        <th>Обложка</th>
                        <th>Год публикации</th>
                        <th width="240px">Действия</th>
                    </tr>
                    {% for book in books %}
                        <tr>
                            <td>{{ book.id }}</td>
                            <td>{{ book.name }}</td>
                            <td>{{ book.getAuthorsList()  }}</td>
                            <td>{{ book.description }}</td>
                            <td><img width="250" height="250" src="data:image/jpg;base64,{{ book.image}}" alt="1" /></td>
                            <td>{{ book.yearPublic }}</td>
                            <td>
                                <form method="post" action="{{ path('app_book_delete', {'id': book.id}) }}" onsubmit="return confirm('Вы действительно хотите удалить запись?');">
                                    <a
                                            class="btn btn-outline-info"
                                            href="{{ path('app_book_show', {'id': book.id}) }}">
                                        Подробнее
                                    </a>
                                    <a
                                            class="btn btn-outline-success"
                                            href="{{ path('app_book_edit', {'id': book.id}) }}">
                                        Редактирование
                                    </a>

                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ book.id) }}">
                                    <button class="btn btn-outline-danger">Удалить</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

{% endblock %}

www/templates/book/new.html.twig
{% extends 'base.html.twig' %}
 
{% block title %}Новая книга{% endblock %}
 
{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Добавить книгу</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_book_index') }}">
                    Показать список книг
                </a>
            </div>
            <div class="card-body">
                {{ include('book/_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

www/templates/book/show.html.twig
{#<!DOCTYPE html>#}

{#<title>Книга</title>#}
{#<style>#}
{#    .styled-table {#}
{#        border-collapse: collapse;#}
{#        margin: 25px 0;#}
{#        font-size: 0.9em;#}
{#        font-family: sans-serif;#}
{#        min-width: 400px;#}
{#        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);#}
{#    }#}
{#    .styled-table thead tr {#}
{#        background-color: #009879;#}
{#        color: #ffffff;#}
{#        text-align: left;#}
{#    }#}

{#    .styled-table th,#}
{#    .styled-table td {#}
{#        padding: 12px 15px;#}
{#    }#}

{#    .styled-table tbody tr {#}
{#        border-bottom: 1px solid #dddddd;#}
{#    }#}

{#    .styled-table tbody tr:nth-of-type(even) {#}
{#        background-color: #f3f3f3;#}
{#    }#}

{#    .styled-table tbody tr:last-of-type {#}
{#        border-bottom: 2px solid #009879;#}
{#    }#}

{#    .styled-table tbody tr.active-row {#}
{#        font-weight: bold;#}
{#        color: #009879;#}
{#    }#}
{#</style>#}
{#{% block body %}#}
{#    <h1>Книга</h1>#}

{#    <table class="styled-table">#}
{#        <tbody>#}
{#            <tr>#}
{#                <th>Id</th>#}
{#                <td>{{ book.id }}</td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th>Название</th>#}
{#                <td>{{ book.name }}</td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th>Описание</th>#}
{#                <td>{{ book.description }}</td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th>Обложка</th>#}
{#                <td>{{ book.image }}</td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th>Год публикации</th>#}
{#                <td>{{ book.yearPublic }}</td>#}
{#            </tr>#}
{#        </tbody>#}
{#    </table>#}

{#    <a href="{{ path('app_book_index') }}">Назад</a>#}

{#    <a href="{{ path('app_book_edit', {'id': book.id}) }}">Обновить</a>#}

{#    {{ include('book/_delete_form.html.twig') }}#}
{#{% endblock %}#}
{% extends 'base.html.twig' %}

{% block title %}Книга{% endblock %}

{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Данные книги</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_book_index') }}">
                    Показать список книг
                </a>
            </div>
            <div class="card-body">
                <b class="text-muted">Название:</b>
                <p>{{ book.name }}</p>
                <b class="text-muted">Описание:</b>
                <p>{{ book.description }}</p>

                <b class="text-muted">Год публикации:</b>
                <p>{{ book.yearPublic }}</p>
                <b class="text-muted">Список авторов:</b>
                <p>{{ book.getAuthorsList() }}</p>
            </div>
            <b class="text-muted">Обложка:</b>
            <img  src="data:image/jpg;base64,{{ book.image}}" alt="1" />
        </div>
    </div>
{% endblock %}